//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightCorona.Localization.Resources.Districts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Districts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Districts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FightCorona.Localization.Resources.Districts.Districts", typeof(Districts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ariyalur.
        /// </summary>
        internal static string Ariyalur {
            get {
                return ResourceManager.GetString("Ariyalur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chengalpattu.
        /// </summary>
        internal static string Chengalpattu {
            get {
                return ResourceManager.GetString("Chengalpattu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chennai.
        /// </summary>
        internal static string Chennai {
            get {
                return ResourceManager.GetString("Chennai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coimbatore.
        /// </summary>
        internal static string Coimbatore {
            get {
                return ResourceManager.GetString("Coimbatore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuddalore.
        /// </summary>
        internal static string Cuddalore {
            get {
                return ResourceManager.GetString("Cuddalore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dharmapuri.
        /// </summary>
        internal static string Dharmapuri {
            get {
                return ResourceManager.GetString("Dharmapuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dindigul.
        /// </summary>
        internal static string Dindigul {
            get {
                return ResourceManager.GetString("Dindigul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erode.
        /// </summary>
        internal static string Erode {
            get {
                return ResourceManager.GetString("Erode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kallakuruchi.
        /// </summary>
        internal static string Kallakuruchi {
            get {
                return ResourceManager.GetString("Kallakuruchi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kancheepuram.
        /// </summary>
        internal static string Kancheepuram {
            get {
                return ResourceManager.GetString("Kancheepuram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanyakumari.
        /// </summary>
        internal static string Kanyakumari {
            get {
                return ResourceManager.GetString("Kanyakumari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karur.
        /// </summary>
        internal static string Karur {
            get {
                return ResourceManager.GetString("Karur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krishnagiri.
        /// </summary>
        internal static string Krishnagiri {
            get {
                return ResourceManager.GetString("Krishnagiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madurai.
        /// </summary>
        internal static string Madurai {
            get {
                return ResourceManager.GetString("Madurai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagapattinam.
        /// </summary>
        internal static string Nagapattinam {
            get {
                return ResourceManager.GetString("Nagapattinam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namakkal.
        /// </summary>
        internal static string Namakkal {
            get {
                return ResourceManager.GetString("Namakkal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nilgris.
        /// </summary>
        internal static string Nilgris {
            get {
                return ResourceManager.GetString("Nilgris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perambalur.
        /// </summary>
        internal static string Perambalur {
            get {
                return ResourceManager.GetString("Perambalur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pudukottai.
        /// </summary>
        internal static string Pudukottai {
            get {
                return ResourceManager.GetString("Pudukottai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramanathapuram.
        /// </summary>
        internal static string Ramanathapuram {
            get {
                return ResourceManager.GetString("Ramanathapuram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranipet.
        /// </summary>
        internal static string Ranipet {
            get {
                return ResourceManager.GetString("Ranipet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salem.
        /// </summary>
        internal static string Salem {
            get {
                return ResourceManager.GetString("Salem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sivaganga.
        /// </summary>
        internal static string Sivaganga {
            get {
                return ResourceManager.GetString("Sivaganga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenkasi.
        /// </summary>
        internal static string Tenkasi {
            get {
                return ResourceManager.GetString("Tenkasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanjavur.
        /// </summary>
        internal static string Thanjavur {
            get {
                return ResourceManager.GetString("Thanjavur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theni.
        /// </summary>
        internal static string Theni {
            get {
                return ResourceManager.GetString("Theni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiruvallur.
        /// </summary>
        internal static string Thiruvallur {
            get {
                return ResourceManager.GetString("Thiruvallur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiruvarur.
        /// </summary>
        internal static string Thiruvarur {
            get {
                return ResourceManager.GetString("Thiruvarur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoothukudi.
        /// </summary>
        internal static string Thoothukudi {
            get {
                return ResourceManager.GetString("Thoothukudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiruchirapalli.
        /// </summary>
        internal static string Tiruchirapalli {
            get {
                return ResourceManager.GetString("Tiruchirapalli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tirunelveli.
        /// </summary>
        internal static string Tirunelveli {
            get {
                return ResourceManager.GetString("Tirunelveli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tirupathur.
        /// </summary>
        internal static string Tirupathur {
            get {
                return ResourceManager.GetString("Tirupathur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiruppur.
        /// </summary>
        internal static string Tiruppur {
            get {
                return ResourceManager.GetString("Tiruppur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiruvannamalai.
        /// </summary>
        internal static string Tiruvannamalai {
            get {
                return ResourceManager.GetString("Tiruvannamalai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmapped.
        /// </summary>
        internal static string Unmapped {
            get {
                return ResourceManager.GetString("Unmapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vellore.
        /// </summary>
        internal static string Vellore {
            get {
                return ResourceManager.GetString("Vellore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villupuram.
        /// </summary>
        internal static string Villupuram {
            get {
                return ResourceManager.GetString("Villupuram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virudhunagar.
        /// </summary>
        internal static string Virudhunagar {
            get {
                return ResourceManager.GetString("Virudhunagar", resourceCulture);
            }
        }
    }
}
