//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightCorona.Localization.Resources.States {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class States {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal States() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FightCorona.Localization.Resources.States.States", typeof(States).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANDAMAN AND NICOBAR ISLAND.
        /// </summary>
        public static string ANDAMANANDNICOBARISLANDS {
            get {
                return ResourceManager.GetString("ANDAMANANDNICOBARISLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANDHRA PRADESH.
        /// </summary>
        public static string ANDHRAPRADESH {
            get {
                return ResourceManager.GetString("ANDHRAPRADESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arunachal Pradesh.
        /// </summary>
        public static string ArunachalPradesh {
            get {
                return ResourceManager.GetString("ArunachalPradesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSAM.
        /// </summary>
        public static string ASSAM {
            get {
                return ResourceManager.GetString("ASSAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIHAR.
        /// </summary>
        public static string BIHAR {
            get {
                return ResourceManager.GetString("BIHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANDIGARH.
        /// </summary>
        public static string CHANDIGARH {
            get {
                return ResourceManager.GetString("CHANDIGARH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHHATTISGARH.
        /// </summary>
        public static string CHHATTISGARH {
            get {
                return ResourceManager.GetString("CHHATTISGARH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DADRA AND NAGAR HAVELI.
        /// </summary>
        public static string DADRAANDNAGAR_HAVELI {
            get {
                return ResourceManager.GetString("DADRAANDNAGAR HAVELI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAMAN AND DIU.
        /// </summary>
        public static string DAMANANDDIU {
            get {
                return ResourceManager.GetString("DAMANANDDIU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELHI.
        /// </summary>
        public static string DELHI {
            get {
                return ResourceManager.GetString("DELHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOA.
        /// </summary>
        public static string GOA {
            get {
                return ResourceManager.GetString("GOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUJARAT.
        /// </summary>
        public static string GUJARAT {
            get {
                return ResourceManager.GetString("GUJARAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARYANA.
        /// </summary>
        public static string HARYANA {
            get {
                return ResourceManager.GetString("HARYANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIMACHAL PRADESH.
        /// </summary>
        public static string HIMACHALPRADESH {
            get {
                return ResourceManager.GetString("HIMACHALPRADESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAMMU AND KASHMIR.
        /// </summary>
        public static string JAMMUANDKASHMIR {
            get {
                return ResourceManager.GetString("JAMMUANDKASHMIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JHARKHAND.
        /// </summary>
        public static string JHARKHAND {
            get {
                return ResourceManager.GetString("JHARKHAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KARNATAKA.
        /// </summary>
        public static string KARNATAKA {
            get {
                return ResourceManager.GetString("KARNATAKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KERALA.
        /// </summary>
        public static string KERALA {
            get {
                return ResourceManager.GetString("KERALA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LADAKH.
        /// </summary>
        public static string LADAKH {
            get {
                return ResourceManager.GetString("LADAKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAKSHADWEEP.
        /// </summary>
        public static string LAKSHADWEEP {
            get {
                return ResourceManager.GetString("LAKSHADWEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADHYA PRADESH.
        /// </summary>
        public static string MADHYAPRADESH {
            get {
                return ResourceManager.GetString("MADHYAPRADESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAHARASHTRA.
        /// </summary>
        public static string MAHARASHTRA {
            get {
                return ResourceManager.GetString("MAHARASHTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANIPUR.
        /// </summary>
        public static string MANIPUR {
            get {
                return ResourceManager.GetString("MANIPUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEGHALAYA.
        /// </summary>
        public static string MEGHALAYA {
            get {
                return ResourceManager.GetString("MEGHALAYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIZORAM.
        /// </summary>
        public static string MIZORAM {
            get {
                return ResourceManager.GetString("MIZORAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAGALAND.
        /// </summary>
        public static string NAGALAND {
            get {
                return ResourceManager.GetString("NAGALAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODISHA.
        /// </summary>
        public static string ODISHA {
            get {
                return ResourceManager.GetString("ODISHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUDUCHERRY.
        /// </summary>
        public static string PUDUCHERRY {
            get {
                return ResourceManager.GetString("PUDUCHERRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUNJAB.
        /// </summary>
        public static string PUNJAB {
            get {
                return ResourceManager.GetString("PUNJAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAJASTHAN.
        /// </summary>
        public static string RAJASTHAN {
            get {
                return ResourceManager.GetString("RAJASTHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIKKIM.
        /// </summary>
        public static string SIKKIM {
            get {
                return ResourceManager.GetString("SIKKIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAMIL NADU.
        /// </summary>
        public static string TAMILNADU {
            get {
                return ResourceManager.GetString("TAMILNADU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELANGANA.
        /// </summary>
        public static string TELANGANA {
            get {
                return ResourceManager.GetString("TELANGANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIPURA.
        /// </summary>
        public static string TRIPURA {
            get {
                return ResourceManager.GetString("TRIPURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTTARAKHAND.
        /// </summary>
        public static string UTTARAKHAND {
            get {
                return ResourceManager.GetString("UTTARAKHAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTTAR PRADESH.
        /// </summary>
        public static string UTTARPRADESH {
            get {
                return ResourceManager.GetString("UTTARPRADESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEST BENGAL.
        /// </summary>
        public static string WESTBENGAL {
            get {
                return ResourceManager.GetString("WESTBENGAL", resourceCulture);
            }
        }
    }
}
